name: Docker Image CI

on:
  push:
    branches: main

jobs:

  build:
    name: Continuous Integration of the endpoint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install CI dependencies
      run: |
        python -m pip install -r .ci/requirements.txt
        python -m pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        flake8 app/
  
    - name: Test with pytest
      run: |
        pytest

    - name: Login to Github Packages
      run: docker login https://docker.pkg.github.com --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }}

    - name: Login to Github Packages
      run: docker login https://docker.pkg.github.com --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push the Docker image
      run: |
        date_tag=$(date +%s)
        docker build . -t docker.pkg.github.com/dernat71/example-cicd/my-example-fastapi-endpoint:$date_tag
        docker push docker.pkg.github.com/dernat71/example-cicd/my-example-fastapi-endpoint:$date_tag
