name: Docker Image CI

on:
  push:
    branches: main

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Login to Github Packages
      run: docker login https://docker.pkg.github.com --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }}

    - name: Build the Docker image
      run: |
        date_tag=$(date +%s)
        docker build . -t docker.pkg.github.com/dernat71/example-cicd/my-example-fastapi-endpoint:$date_tag

    - name: Push the image to Github Packages
      run: docker push docker.pkg.github.com/dernat71/example-cicd/my-example-fastapi-endpoint:$date_tag

    # - name: Push to GitHub Packages
    #   uses: docker/build-push-action@v1
    #   with:
    #     username: ${{ github.actor }}
    #     password: ${{ secrets.GITHUB_TOKEN }}
    #     registry: docker.pkg.github.com
    #     repository: dernat71/example-cicd/my-example-fastapi-endpoint
    #     tag_with_ref: true
