name: Master CICD Pipeline

on:
  push:
    branches: main

jobs:

  build:
    name: Continuous Integration of the endpoint
    runs-on: ubuntu-latest
    steps:
    - name: login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: |
        git_hash=$(git rev-parse --short HEAD)
        docker build . -t ghcr.io/${{ github.actor }}/example-cicd/my-example-fastapi-endpoint:$git_hash

    - name: Test the Docker image
      run: |
        git_hash=$(git rev-parse --short HEAD)
        docker run \
        --entrypoint=/bin/bash \
        ghcr.io/${{ github.actor }}/example-cicd/my-example-fastapi-endpoint:$git_hash \
        ./script/test

    - name: Login and push the Docker image to Github Packages
      run: |
        git_hash=$(git rev-parse --short HEAD)
        docker push ghcr.io/${{ github.actor }}/example-cicd/my-example-fastapi-endpoint:$git_hash
