name: Master CICD Pipeline

on:
  push:
    branches: main

jobs:

  build:
    name: Continuous Integration of the endpoint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: |
        git_hash=$(git rev-parse --short HEAD)
        docker build . -t ghcr.io/cedricdeboom/example-cicd/my-example-fastapi-endpoint:$git_hash
      env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Test the Docker image
      run: |
        git_hash=$(git rev-parse --short HEAD)
        docker run \
        --entrypoint=/bin/bash \
        docker build . -t ghcr.io/cedricdeboom/example-cicd/my-example-fastapi-endpoint:$git_hash \
        ./script/test
      env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Login and push the Docker image to Github Packages
      run: |
        git_hash=$(git rev-parse --short HEAD)
        docker push docker.pkg.github.com/dernat71/example-cicd/my-example-fastapi-endpoint:$git_hash
      env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
